### ISSUE TITLE
No action when clicking "Select File"

### ISSUE THREAD

**Issue by novitae** [jayarajrohan/Webp-to-Gif-Converter#1]
in the term, printing `2021-10-15 18:11:15.386 Python[11328:254261] -[QNSApplication macOSVersion]: unrecognized selector sent to instance 0x7fae50a99040`

**Comment by jayarajrohan** [comment]
> in the term, printing `2021-10-15 18:11:15.386 Python[11328:254261] -[QNSApplication macOSVersion]: unrecognized selector sent to instance 0x7fae50a99040`

In which operating system are you trying to run? Is it mac?

**Comment by novitae** [comment]
it is yes

**Comment by jayarajrohan** [comment]
This Webp to Gif Converter is for the windows operating system.  This might be the reason.
